<a href="https://colab.research.google.com/github/Mammad-AI/IAAA_MMD_AI/blob/main/first_densenet_for_iaaa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install the necessary packages for working with DICOM files and MONAI
!pip install pydicom
!pip install monai


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 65.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 49.0 MB/s eta 0:00:00


In [2]:
# Uploading files from the user's local system
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"mohammadpourmazahery","key":"6fea11414884209611b85dbd61351ce5"}'}

In [3]:
from monai.transforms import (
    Compose, LoadImage, EnsureChannelFirstD, ScaleIntensity, Resize, ToTensor,
    RandFlip, RandRotate90, RandScaleIntensity, RandShiftIntensity
)
from monai.networks.nets import UNet, UNETR, SegResNet
from monai.data import DataLoader, Dataset
from monai.inferers import sliding_window_inference

In [4]:
import monai
from monai.apps import download_and_extract

In [5]:
# Importing the necessary libraries for data processing and model building
import random
import pandas as pd  # For handling CSV files and dataframes
import os  # For interacting with the file system
import pydicom  # For working with DICOM files
import matplotlib.pyplot as plt  # For visualizations
import seaborn as sns  # For enhanced data visualizations
from tqdm import tqdm  # For progress bars in loops
import pydicom as dicom  # Alias for pydicom
from pydicom import dcmread  # To read DICOM files
from pydicom.data import get_testdata_file  # To access sample DICOM data
from pydicom.pixel_data_handlers.util import apply_voi_lut  # Utility to handle DICOM pixel data transformations
import torchvision.models as models  # For pre-trained models
import numpy as np  # For array manipulations
from sklearn.metrics import accuracy_score  # For evaluating classification models
from tensorflow.keras.preprocessing.image import load_img, img_to_array  # For image preprocessing in Keras
from natsort import natsorted  # For natural sorting
import cv2  # For image processing
import math  # For mathematical operations
from torch.utils.data import DataLoader, Dataset  # For creating datasets and loading data in PyTorch
import torch.nn.functional as F  # For using various functions in PyTorch
import torch.nn as nn  # For building neural networks
import torch.optim as optim  # For optimization algorithms
from sklearn.model_selection import KFold  # For K-Fold cross-validation
import sys  # For system-related functions
import torch  # PyTorch library


from monai.networks.nets import DenseNet121  # For using DenseNet architecture
from monai.data import Dataset, CacheDataset  # For handling medical datasets
from monai.utils import set_determinism  # For reproducibility in training


In [6]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [7]:
# Set up Kaggle API credentials for downloading the dataset
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json  # Set permissions for the Kaggle JSON file



In [8]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [71]:
model = monai.networks.nets.DenseNet121(spatial_dims=3, in_channels=1, out_channels=2)
model.features.transition3.pool=nn.AvgPool3d(kernel_size=(1,2,2), stride=(1,2,2))
model.class_layers.out = nn.Sequential(
    nn.Linear(1024, 2),  # Replace 1024 with the actual input size of your fc layer
    nn.Softmax(dim=1)  # Apply softmax activation
)
model.to(device)

DenseNet121(
  (features): Sequential(
    (conv0): Conv3d(1, 64, kernel_size=(7, 7, 7), stride=(2, 2, 2), padding=(3, 3, 3), bias=False)
    (norm0): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu0): ReLU(inplace=True)
    (pool0): MaxPool3d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (denseblock1): _DenseBlock(
      (denselayer1): _DenseLayer(
        (layers): Sequential(
          (norm1): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu1): ReLU(inplace=True)
          (conv1): Conv3d(64, 128, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
          (norm2): BatchNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu2): ReLU(inplace=True)
          (conv2): Conv3d(128, 32, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1), bias=False)
        )
      )
      (denselayer2): _DenseLayer(
        (layers): Sequential(
 

In [11]:
# Download and unzip the MRI dataset from Kaggle
!kaggle datasets download -d iaaaplatform/iaaa-mri-challenge
!unzip iaaa-mri-challenge.zip

Streaming output truncated to the last 5000 lines.
  inflating: data/1.3.46.670589.11.10042.5.0.7984.2024022407234101045/1.3.46.670589.11.10042.5.0.7984.2024022407242432073.dcm  
  inflating: data/1.3.46.670589.11.10042.5.0.7984.2024022407234101045/1.3.46.670589.11.10042.5.0.7984.2024022407242437074.dcm  
  inflating: data/1.3.46.670589.11.10042.5.0.7984.2024022407234101045/1.3.46.670589.11.10042.5.0.7984.2024022407242443075.dcm  
  inflating: data/1.3.46.670589.11.10042.5.0.7984.2024022407234101045/1.3.46.670589.11.10042.5.0.7984.2024022407242448076.dcm  
  inflating: data/1.3.46.670589.11.10042.5.0.7984.2024022407234101045/1.3.46.670589.11.10042.5.0.7984.2024022407242453077.dcm  
  inflating: data/1.3.46.670589.11.10042.5.0.7984.2024022407234101045/1.3.46.670589.11.10042.5.0.7984.2024022407245301078.dcm  
  inflating: data/1.3.46.670589.11.10042.5.0.7984.2024022407234101045/1.3.46.670589.11.10042.5.0.7984.2024022407245306079.dcm  
  inflating: data/1.3.46.670589.11.10042.5.0.7984.202

In [12]:
# Define paths and load the training labels from the CSV file
data_dir = 'data'
train_label = pd.read_csv('train.csv')



In [13]:
# Function to sort DICOM files by slice number based on a specific DICOM tag
def sort_dicom_files(paths):
    sorted_files = [np.nan] * 24  # Initialize a list to store sorted files
    for i in range(len(paths)):
        dicom = pydicom.dcmread(paths[i])  # Read each DICOM file
        slice_number_mr_tag = (0x2001, 0x100a)  # DICOM tag for slice number
        slice_number_mr_value = int(dicom[slice_number_mr_tag].value)  # Get the slice number
        sorted_files[(slice_number_mr_value - 1)] = paths[i]  # Place the file in the correct position
    filtered_paths = [path for path in sorted_files if not isinstance(path, float)]  # Remove empty slots
    return filtered_paths  # Return the sorted list of paths


In [14]:
# Function to generate labels based on the `SeriesInstanceUID`
def produce_label(SeriesInstanceUID, train_label):
    label = train_label[train_label.SeriesInstanceUID == SeriesInstanceUID].prediction
    # If no label is found, default to [1,0]
    if label.empty:
        label = torch.tensor([1, 0])
    else:
        if label.iloc[0] == 0:
            label = torch.tensor([1, 0])
        else:
            label = torch.tensor([0, 1])
    return label



In [15]:
# Function to standardize DICOM files and resize them to a specific shape
def standardize_dicom(serie_id):
    path1 = f'data/{serie_id}'
    paths = []
    for i in os.listdir(path1):
        paths.append(os.path.join(path1, i))
    paths = sort_dicom_files(paths)  # Sort the DICOM files in the correct order
    dicom_3d = []
    for i in range(len(paths)):
        dir = paths[i]
        dicom_pix = pydicom.dcmread(dir).pixel_array  # Read the pixel data from the DICOM file
        dicom_pix = dicom_pix / dicom_pix.max()  # Normalize the pixel data
        dicom_3d.append(dicom_pix)  # Append the slice to the list
    dicom_3d = np.array(dicom_3d)  # Convert the list to a NumPy array
    dicom_3d = torch.tensor(dicom_3d)  # Convert the array to a PyTorch tensor
    dicom_3d = dicom_3d.unsqueeze(0)  # Add a channel dimension
    dicom_3d = dicom_3d.unsqueeze(0)  # Add a batch dimension
    dicom_3d = F.interpolate(dicom_3d, (16, 288, 288), mode='trilinear', align_corners=False)  # Resize the data to the required shape
    return dicom_3d  # Return the standardized DICOM data



In [16]:
# Custom dataset class for DICOM data
class DICOMDataset(Dataset):
    def __init__(self, series_list, produce_label, data_dir, transform=None):
        self.series_list = series_list  # List of series IDs
        self.produce_label = produce_label  # Function to produce labels
        self.data_dir = data_dir  # Directory containing the data
        self.transform = transform  # Transformations to be applied to the data

    def __len__(self):
        return len(self.series_list)  # Return the length of the dataset

    def __getitem__(self, idx):
        series_id = self.series_list[idx]  # Get the series ID for the current index
        final_input = standardize_dicom(series_id)  # Standardize the DICOM files for this series
        final_label = produce_label(series_id, train_label)  # Get the corresponding label
        final_input = final_input.clone().detach()  # Detach the tensor from the computation graph
        if self.transform:
            final_input = self.transform(final_input)  # Apply any transformations
        return final_input, final_label  # Return the input and label


In [17]:
# Freezing all model layers initially
for param in model.parameters():
    param.requires_grad = False


In [68]:

criterion = nn.CrossEntropyLoss()  # Mean Squared Error Loss
total_itteration=5
b=0
optimizer = optim.Adam(model.parameters(), lr=0.001)  # Adam optimizer with learning rate 0.001


In [19]:
def unfreeze_layers(model, num_layers_to_unfreeze, device):
    """
    Unfreeze the last `num_layers_to_unfreeze` layers of the model.
    Move the unfrozen layers to the specified device.
    """
    layers = list(model.children())
    for layer in layers[num_layers_to_unfreeze:]:
        for param in layer.parameters():
            param.requires_grad = True
        layer.to(device) # Move the unfrozen layer to the device

In [20]:
layers=list(model.features+model.class_layers)

In [21]:
layers_to_unfreeze=[-1,-6,-7,-8,-9,-10,-11,-12,-16]

In [22]:
epoch=len(layers_to_unfreeze)

In [23]:
abnormal_series_id=train_label[train_label.prediction==1].SeriesInstanceUID

In [24]:
normal_series_id=train_label[train_label.prediction==0].SeriesInstanceUID

In [51]:
series_list=np.concatenate((abnormal_series_id,np.random.choice(normal_series_id,391)))
random.shuffle(series_list)

In [26]:
kf=KFold(n_splits=3,shuffle=True,random_state=42)

In [ ]:
for i in range(total_itteration):
    series_list=np.concatenate((abnormal_series_id,np.random.choice(normal_series_id,391)))
    random.shuffle(series_list)
    num_epochs=len(layers_to_unfreeze)
    best_val_loss = float('inf')
    save_dir='saved_models'
    os.makedirs(save_dir, exist_ok=True)  # Create the directory if it does not exist
    best_model_path = os.path.join(save_dir, 'best_model.pth')
    for train_index, test_index in kf.split(series_list):
        train_series_list, test_series_list = series_list[train_index], series_list[test_index]
        train_dataset = DICOMDataset(train_series_list, produce_label, data_dir)
        val_dataset = DICOMDataset(test_series_list, produce_label, data_dir)
        train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, num_workers=4)
        val_loader = DataLoader(val_dataset, batch_size=4, shuffle=False, num_workers=4)
        # Training loop for this fold

        for epoch in range(len(layers_to_unfreeze)):
            for param in model.parameters():
                param.requires_grad = False

            unfreeze_layers(model, layers_to_unfreeze[epoch],device)  # Gradually unfreeze layers

        # Update the optimizer to include all trainable parameters
            optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=(0.001/(epoch+b+i)))
            model.train()
            running_loss=0.0
            for batch in tqdm(train_loader):
                inputs, labels = batch
                labels=labels.float()
                inputs = inputs.float()  # Convert inputs to float type
                inputs = inputs.squeeze(2) # Remove the extra dimension at index 2
                inputs, labels = inputs.to(device), labels.to(device)  # Move data to GPU
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                running_loss += loss.item()
                loss.backward()
                optimizer.step()


            model.eval()
            torch.cuda.empty_cache()

            val_loss = 0.0
            with torch.no_grad():
                for batch in tqdm(val_loader):
                    inputs, labels = batch
                    inputs = inputs.float()  # Convert inputs to float type
                    inputs = inputs.to(device)
                    inputs=inputs.squeeze(2)
                    labels = labels.to(device)

                    outputs = model(inputs)
                    loss = criterion(outputs, labels.float())
                    val_loss += loss.item()
            torch.cuda.empty_cache()
            val_loss /= len(val_loader)
            print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {running_loss/len(train_loader)}, Val Loss: {val_loss}')
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                torch.save(model.state_dict(), best_model_path)
                print(f'Best model saved with validation loss: {best_val_loss}')
            print(outputs)
            print(labels)
        print(f'number of total kf={b}')
    print(f'number of total itteration={i}')
    best_model_weights = torch.load(best_model_path)
    model.load_state_dict(best_model_weights)
    print(i)


100%|██████████| 66/66 [00:13<00:00,  4.97it/s]


Epoch 1/9, Train Loss: 0.5218864187939476, Val Loss: 0.45103871867512213
Best model saved with validation loss: 0.45103871867512213
tensor([[0.2436, 0.7564]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.95it/s]


Epoch 2/9, Train Loss: 0.5096381998244133, Val Loss: 0.4388573363874898
Best model saved with validation loss: 0.4388573363874898
tensor([[0.9961, 0.0039]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.95it/s]


Epoch 3/9, Train Loss: 0.4955349305203853, Val Loss: 0.4354424833348303
Best model saved with validation loss: 0.4354424833348303
tensor([[9.9976e-01, 2.3888e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.05it/s]


Epoch 4/9, Train Loss: 0.5128309633440644, Val Loss: 0.45556974140080536
tensor([[0.9959, 0.0041]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.02it/s]


Epoch 5/9, Train Loss: 0.4946426737854499, Val Loss: 0.45210767018072534
tensor([[0.8303, 0.1697]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.05it/s]


Epoch 6/9, Train Loss: 0.4949571456162984, Val Loss: 0.5019084653168013
tensor([[9.9970e-01, 3.0084e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.10it/s]


Epoch 7/9, Train Loss: 0.4572348544615826, Val Loss: 0.4336415502158078
Best model saved with validation loss: 0.4336415502158078
tensor([[9.9977e-01, 2.2760e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.00it/s]


Epoch 8/9, Train Loss: 0.45901423101206773, Val Loss: 0.4740349921313199
tensor([[0.9977, 0.0023]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.00it/s]


Epoch 9/9, Train Loss: 0.4537314738481099, Val Loss: 0.4594904748779355
tensor([[9.9979e-01, 2.0681e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')
number of total kf=12


100%|██████████| 66/66 [00:12<00:00,  5.11it/s]


Epoch 1/9, Train Loss: 0.49378769497835, Val Loss: 0.36958421540982794
Best model saved with validation loss: 0.36958421540982794
tensor([[9.9967e-01, 3.2746e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.08it/s]


Epoch 2/9, Train Loss: 0.5145407921940316, Val Loss: 0.39338801169034204
tensor([[9.9958e-01, 4.2228e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.21it/s]


Epoch 3/9, Train Loss: 0.49950356701858173, Val Loss: 0.40644934502514923
tensor([[9.9999e-01, 1.3933e-05]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.05it/s]


Epoch 4/9, Train Loss: 0.49215978065519844, Val Loss: 0.4210873440359578
tensor([[9.9997e-01, 2.5195e-05]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.22it/s]


Epoch 5/9, Train Loss: 0.4747236164016578, Val Loss: 0.4821957309137691
tensor([[9.9986e-01, 1.4305e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.19it/s]


Epoch 6/9, Train Loss: 0.4504949871365351, Val Loss: 0.4133619982184786
tensor([[9.9985e-01, 1.4843e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.22it/s]


Epoch 7/9, Train Loss: 0.4863227362396153, Val Loss: 0.40241929617795075
tensor([[0.9922, 0.0078]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.00it/s]


Epoch 8/9, Train Loss: 0.4686297694690355, Val Loss: 0.3917486590869499
tensor([[0.9981, 0.0019]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.16it/s]


Epoch 9/9, Train Loss: 0.4612753500465218, Val Loss: 0.4016495699232275
tensor([[9.9988e-01, 1.2190e-04]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')
number of total kf=12


100%|██████████| 65/65 [00:12<00:00,  5.05it/s]


Epoch 1/9, Train Loss: 0.4542359277492261, Val Loss: 0.36326737724817715
Best model saved with validation loss: 0.36326737724817715
tensor([[9.9798e-01, 2.0173e-03],
        [8.6711e-01, 1.3289e-01],
        [4.4536e-04, 9.9955e-01],
        [3.8193e-01, 6.1807e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.10it/s]


Epoch 2/9, Train Loss: 0.48311534501214065, Val Loss: 0.38515904958431535
tensor([[9.9968e-01, 3.1610e-04],
        [2.5732e-01, 7.4268e-01],
        [7.7243e-06, 9.9999e-01],
        [2.1251e-02, 9.7875e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.11it/s]


Epoch 3/9, Train Loss: 0.4845557399378478, Val Loss: 0.38257329830756553
tensor([[1.0000e+00, 4.8014e-06],
        [8.2532e-01, 1.7468e-01],
        [1.0463e-06, 1.0000e+00],
        [5.0183e-02, 9.4982e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.07it/s]


Epoch 4/9, Train Loss: 0.4737326075102537, Val Loss: 0.4377065979517423
tensor([[9.9999e-01, 6.6372e-06],
        [9.9929e-01, 7.0810e-04],
        [3.6003e-05, 9.9996e-01],
        [9.9943e-01, 5.6855e-04]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.97it/s]


Epoch 5/9, Train Loss: 0.4592067487822234, Val Loss: 0.4287406316170326
tensor([[9.9927e-01, 7.3404e-04],
        [8.2768e-02, 9.1723e-01],
        [1.5315e-06, 1.0000e+00],
        [1.0498e-02, 9.8950e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.95it/s]


Epoch 6/9, Train Loss: 0.4552003395466404, Val Loss: 0.44612661966910727
tensor([[9.1188e-01, 8.8122e-02],
        [1.8670e-02, 9.8133e-01],
        [6.5768e-07, 1.0000e+00],
        [1.0014e-02, 9.8999e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.98it/s]


Epoch 7/9, Train Loss: 0.43733082040575627, Val Loss: 0.37658586639624375
tensor([[9.9507e-01, 4.9255e-03],
        [9.6390e-01, 3.6097e-02],
        [1.3309e-05, 9.9999e-01],
        [9.8562e-01, 1.4384e-02]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.03it/s]


Epoch 8/9, Train Loss: 0.45277154445648193, Val Loss: 0.38455901466883147
tensor([[9.9973e-01, 2.7043e-04],
        [9.9861e-01, 1.3910e-03],
        [6.5429e-06, 9.9999e-01],
        [9.9989e-01, 1.0779e-04]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.99it/s]
<ipython-input-85-5c99c5b998ce>:67: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  best_model_weights = torch.load(best_model_

Epoch 9/9, Train Loss: 0.4115004041267715, Val Loss: 0.39876589041489824
tensor([[9.9999e-01, 6.7209e-06],
        [9.9961e-01, 3.8808e-04],
        [6.3631e-07, 1.0000e+00],
        [9.9998e-01, 1.5285e-05]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [0, 1],
        [1, 0]], device='cuda:0')
number of total kf=12
number of total itteration=0
0


100%|██████████| 66/66 [00:13<00:00,  5.02it/s]


Epoch 1/9, Train Loss: 0.49450797661570195, Val Loss: 0.4247306607889407
Best model saved with validation loss: 0.4247306607889407
tensor([[6.5480e-11, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.99it/s]


Epoch 2/9, Train Loss: 0.47173632851993763, Val Loss: 0.4978927464196176
tensor([[3.9834e-07, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.01it/s]


Epoch 3/9, Train Loss: 0.4513664659653001, Val Loss: 0.43247237982171954
tensor([[3.4895e-09, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.09it/s]


Epoch 4/9, Train Loss: 0.4541200788421485, Val Loss: 0.46028626958529156
tensor([[2.9961e-06, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.13it/s]


Epoch 5/9, Train Loss: 0.47173011826194877, Val Loss: 0.5100208715055928
tensor([[3.5870e-09, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.96it/s]


Epoch 6/9, Train Loss: 0.4344374287219448, Val Loss: 0.42246222947583056
Best model saved with validation loss: 0.42246222947583056
tensor([[1.7620e-07, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.10it/s]


Epoch 7/9, Train Loss: 0.44388855663874677, Val Loss: 0.4317648261785507
tensor([[1.7580e-09, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.04it/s]


Epoch 8/9, Train Loss: 0.4559279607452509, Val Loss: 0.434576100472248
tensor([[1.7700e-07, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.98it/s]


Epoch 9/9, Train Loss: 0.4145753292637017, Val Loss: 0.4643064651525382
tensor([[2.4461e-06, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')
number of total kf=12


100%|██████████| 66/66 [00:13<00:00,  5.02it/s]


Epoch 1/9, Train Loss: 0.46216491911247487, Val Loss: 0.3437972181674206
Best model saved with validation loss: 0.3437972181674206
tensor([[5.0503e-04, 9.9949e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.02it/s]


Epoch 2/9, Train Loss: 0.4691242022823741, Val Loss: 0.4712817384438081
tensor([[3.7681e-06, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.11it/s]


Epoch 3/9, Train Loss: 0.46513729536806353, Val Loss: 0.37987151877446607
tensor([[3.3133e-04, 9.9967e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.00it/s]


Epoch 4/9, Train Loss: 0.4560480543220316, Val Loss: 0.4305455233111526
tensor([[1.9525e-05, 9.9998e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.15it/s]


Epoch 5/9, Train Loss: 0.4471677500783032, Val Loss: 0.4655134429534276
tensor([[1.5925e-06, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.94it/s]


Epoch 6/9, Train Loss: 0.46723255583348167, Val Loss: 0.3932218217488491
tensor([[1.5448e-04, 9.9985e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.89it/s]


Epoch 7/9, Train Loss: 0.4295164025921858, Val Loss: 0.39205738856936945
tensor([[1.5116e-04, 9.9985e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.82it/s]


Epoch 8/9, Train Loss: 0.4451135326432818, Val Loss: 0.41978124190460553
tensor([[4.7075e-07, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.92it/s]


Epoch 9/9, Train Loss: 0.4203113301564719, Val Loss: 0.3947468002637227
tensor([[0.0021, 0.9979]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')
number of total kf=12


100%|██████████| 65/65 [00:13<00:00,  4.84it/s]


Epoch 1/9, Train Loss: 0.4163695662531234, Val Loss: 0.343859614775731
tensor([[9.9842e-01, 1.5806e-03],
        [7.3065e-25, 1.0000e+00],
        [9.9968e-01, 3.1545e-04],
        [1.5920e-05, 9.9998e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.93it/s]


Epoch 2/9, Train Loss: 0.46134108191228096, Val Loss: 0.3622670971430265
tensor([[9.9948e-01, 5.1518e-04],
        [1.2120e-27, 1.0000e+00],
        [1.0000e+00, 1.3297e-06],
        [9.2799e-05, 9.9991e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.09it/s]


Epoch 3/9, Train Loss: 0.4737125480448017, Val Loss: 0.3692170367791103
tensor([[8.6808e-01, 1.3192e-01],
        [0.0000e+00, 1.0000e+00],
        [9.9281e-01, 7.1864e-03],
        [9.1286e-05, 9.9991e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.07it/s]


Epoch 4/9, Train Loss: 0.44648973586905094, Val Loss: 0.3907641832645123
tensor([[9.9971e-01, 2.9428e-04],
        [3.8530e-25, 1.0000e+00],
        [9.9480e-01, 5.2048e-03],
        [1.1864e-06, 1.0000e+00]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.09it/s]


Epoch 5/9, Train Loss: 0.4184219184267612, Val Loss: 0.3835253683420328
tensor([[9.9825e-01, 1.7516e-03],
        [3.5710e-25, 1.0000e+00],
        [9.9982e-01, 1.7637e-04],
        [3.3547e-06, 1.0000e+00]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.08it/s]


Epoch 6/9, Train Loss: 0.449682021186552, Val Loss: 0.3702397901278276
tensor([[9.9992e-01, 8.0090e-05],
        [1.0222e-28, 1.0000e+00],
        [9.9796e-01, 2.0413e-03],
        [5.0421e-05, 9.9995e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.05it/s]


Epoch 7/9, Train Loss: 0.4465144956839904, Val Loss: 0.4204732743593363
tensor([[9.9983e-01, 1.6658e-04],
        [9.5008e-43, 1.0000e+00],
        [9.0712e-01, 9.2877e-02],
        [2.4186e-02, 9.7581e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.02it/s]


Epoch 8/9, Train Loss: 0.4163443534883834, Val Loss: 0.381710691176928
tensor([[9.9999e-01, 1.3952e-05],
        [7.0065e-45, 1.0000e+00],
        [9.9737e-01, 2.6319e-03],
        [2.3464e-02, 9.7654e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.98it/s]


Epoch 9/9, Train Loss: 0.41474268158883537, Val Loss: 0.4042505521040696
tensor([[9.9998e-01, 1.7488e-05],
        [0.0000e+00, 1.0000e+00],
        [9.9999e-01, 5.9320e-06],
        [8.9122e-03, 9.9109e-01]], device='cuda:0')
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')
number of total kf=12
number of total itteration=1
1


100%|██████████| 66/66 [00:13<00:00,  4.94it/s]


Epoch 1/9, Train Loss: 0.47493875072202607, Val Loss: 0.36962372922536096
Best model saved with validation loss: 0.36962372922536096
tensor([[0.0245, 0.9755]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.04it/s]


Epoch 2/9, Train Loss: 0.4816256893500117, Val Loss: 0.41706761853261426
tensor([[0.0078, 0.9922]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.00it/s]


Epoch 3/9, Train Loss: 0.47478248804580164, Val Loss: 0.38773028642842267
tensor([[0.0024, 0.9976]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.96it/s]


Epoch 4/9, Train Loss: 0.46992999133262925, Val Loss: 0.4038515741174871
tensor([[0.0070, 0.9930]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.96it/s]


Epoch 5/9, Train Loss: 0.45033915329525487, Val Loss: 0.45908926743449585
tensor([[0.0273, 0.9727]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.98it/s]


Epoch 6/9, Train Loss: 0.4688753392405182, Val Loss: 0.4016037050521735
tensor([[5.9780e-04, 9.9940e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.95it/s]


Epoch 7/9, Train Loss: 0.458954305594204, Val Loss: 0.4146352748979222
tensor([[0.0083, 0.9917]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.04it/s]


Epoch 8/9, Train Loss: 0.43113057212975187, Val Loss: 0.5083633421948461
tensor([[1.2601e-06, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.02it/s]


Epoch 9/9, Train Loss: 0.44200786766205125, Val Loss: 0.4238544458692724
tensor([[2.2707e-04, 9.9977e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')
number of total kf=12


100%|██████████| 66/66 [00:13<00:00,  4.82it/s]


Epoch 1/9, Train Loss: 0.44814044373636025, Val Loss: 0.3694184706969695
Best model saved with validation loss: 0.3694184706969695
tensor([[8.9487e-06, 9.9999e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.94it/s]


Epoch 2/9, Train Loss: 0.44092959552320815, Val Loss: 0.3961345986886458
tensor([[6.9998e-07, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.85it/s]


Epoch 3/9, Train Loss: 0.4319209904616116, Val Loss: 0.43156595528125763
tensor([[8.5962e-08, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.79it/s]


Epoch 4/9, Train Loss: 0.4418114253127848, Val Loss: 0.40488530334198114
tensor([[3.7200e-10, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.82it/s]


Epoch 5/9, Train Loss: 0.44687256353502053, Val Loss: 0.3959030946998885
tensor([[1.1872e-09, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.92it/s]


Epoch 6/9, Train Loss: 0.42282458844075677, Val Loss: 0.42293312107071734
tensor([[3.4641e-08, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.87it/s]


Epoch 7/9, Train Loss: 0.41554107625065867, Val Loss: 0.412546535784548
tensor([[3.1730e-06, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.92it/s]


Epoch 8/9, Train Loss: 0.44398151417724957, Val Loss: 0.3996270520217491
tensor([[2.4703e-04, 9.9975e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.84it/s]


Epoch 9/9, Train Loss: 0.4275826952839626, Val Loss: 0.40505875782533124
tensor([[1.6474e-04, 9.9984e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')
number of total kf=12


100%|██████████| 65/65 [00:13<00:00,  4.92it/s]


Epoch 1/9, Train Loss: 0.4755286421939617, Val Loss: 0.335664648276109
Best model saved with validation loss: 0.335664648276109
tensor([[6.6264e-06, 9.9999e-01],
        [1.0000e+00, 2.6060e-06],
        [1.0000e+00, 3.0528e-06],
        [5.0596e-03, 9.9494e-01]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  5.00it/s]


Epoch 2/9, Train Loss: 0.46769225415382676, Val Loss: 0.39448154247724093
tensor([[2.2666e-03, 9.9773e-01],
        [1.0000e+00, 3.1330e-06],
        [9.8115e-01, 1.8845e-02],
        [4.6268e-04, 9.9954e-01]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.97it/s]


Epoch 3/9, Train Loss: 0.46007183125910867, Val Loss: 0.38462425149404084
tensor([[8.2788e-11, 1.0000e+00],
        [9.8514e-01, 1.4855e-02],
        [9.9816e-01, 1.8362e-03],
        [3.1771e-02, 9.6823e-01]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.08it/s]


Epoch 4/9, Train Loss: 0.45279670785401616, Val Loss: 0.43781862946657035
tensor([[9.1512e-01, 8.4877e-02],
        [1.0000e+00, 2.4559e-08],
        [1.0000e+00, 6.0129e-07],
        [8.6477e-01, 1.3523e-01]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.92it/s]


Epoch 5/9, Train Loss: 0.44002230681535853, Val Loss: 0.3546999344458947
tensor([[6.5542e-05, 9.9993e-01],
        [9.9940e-01, 5.9646e-04],
        [9.8682e-01, 1.3178e-02],
        [2.3118e-02, 9.7688e-01]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.97it/s]


Epoch 6/9, Train Loss: 0.4456012239892974, Val Loss: 0.43142826786408056
tensor([[6.0183e-03, 9.9398e-01],
        [9.9553e-01, 4.4660e-03],
        [4.5688e-02, 9.5431e-01],
        [1.1168e-06, 1.0000e+00]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.03it/s]


Epoch 7/9, Train Loss: 0.427953127686304, Val Loss: 0.3436158129802117
tensor([[2.2774e-05, 9.9998e-01],
        [9.9997e-01, 2.5174e-05],
        [9.8842e-01, 1.1576e-02],
        [1.9438e-02, 9.8056e-01]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  4.89it/s]


Epoch 8/9, Train Loss: 0.42279339564665586, Val Loss: 0.35440706473130446
tensor([[4.5484e-03, 9.9545e-01],
        [1.0000e+00, 8.8078e-07],
        [9.9324e-01, 6.7556e-03],
        [1.1238e-03, 9.9888e-01]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.05it/s]


Epoch 9/9, Train Loss: 0.40156153299426306, Val Loss: 0.49125295877456665
tensor([[2.8011e-08, 1.0000e+00],
        [9.8993e-01, 1.0071e-02],
        [5.0803e-01, 4.9197e-01],
        [2.1322e-07, 1.0000e+00]], device='cuda:0')
tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1]], device='cuda:0')
number of total kf=12
number of total itteration=2
2


100%|██████████| 66/66 [00:13<00:00,  4.99it/s]


Epoch 1/9, Train Loss: 0.46454794921037806, Val Loss: 0.39635467077746533
Best model saved with validation loss: 0.39635467077746533
tensor([[9.9996e-01, 4.4880e-05]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.95it/s]


Epoch 2/9, Train Loss: 0.45684753824736324, Val Loss: 0.592828737966942
tensor([[0.0036, 0.9964]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.01it/s]


Epoch 3/9, Train Loss: 0.444732794552359, Val Loss: 0.47015000428214215
tensor([[9.9999e-01, 5.5048e-06]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.00it/s]


Epoch 4/9, Train Loss: 0.4505954007156023, Val Loss: 0.4030161287748452
tensor([[0.8791, 0.1209]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.02it/s]


Epoch 5/9, Train Loss: 0.45766279192371223, Val Loss: 0.40652814642949536
tensor([[1.0000e+00, 9.8751e-07]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.99it/s]


Epoch 6/9, Train Loss: 0.4322313502544665, Val Loss: 0.37928904683300946
Best model saved with validation loss: 0.37928904683300946
tensor([[9.9996e-01, 3.8404e-05]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.82it/s]


Epoch 7/9, Train Loss: 0.4217451414989151, Val Loss: 0.38357448623035895
tensor([[0.9984, 0.0016]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.87it/s]


Epoch 8/9, Train Loss: 0.4322357889805131, Val Loss: 0.4530351956685384
tensor([[0.6191, 0.3809]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.17it/s]


Epoch 9/9, Train Loss: 0.4244983608031091, Val Loss: 0.41164934499697253
tensor([[0.9982, 0.0018]], device='cuda:0')
tensor([[1, 0]], device='cuda:0')
number of total kf=12


100%|██████████| 66/66 [00:13<00:00,  4.95it/s]


Epoch 1/9, Train Loss: 0.4317049702615228, Val Loss: 0.338137891256448
Best model saved with validation loss: 0.338137891256448
tensor([[1.2665e-04, 9.9987e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.03it/s]


Epoch 2/9, Train Loss: 0.44465513743517054, Val Loss: 0.35811001694563666
tensor([[1.1603e-04, 9.9988e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.03it/s]


Epoch 3/9, Train Loss: 0.46136254026689605, Val Loss: 0.36903070906798047
tensor([[1.2401e-05, 9.9999e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.02it/s]


Epoch 4/9, Train Loss: 0.4405233839540991, Val Loss: 0.3513620897676005
tensor([[0.0152, 0.9848]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.04it/s]


Epoch 5/9, Train Loss: 0.42818470447118046, Val Loss: 0.38642049558234937
tensor([[8.9268e-09, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:12<00:00,  5.11it/s]


Epoch 6/9, Train Loss: 0.4234377323216154, Val Loss: 0.3956643216537707
tensor([[3.7448e-07, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.03it/s]


Epoch 7/9, Train Loss: 0.399819627062965, Val Loss: 0.35854902321642096
tensor([[3.9224e-04, 9.9961e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.07it/s]


Epoch 8/9, Train Loss: 0.4138195125656274, Val Loss: 0.4639610679763736
tensor([[3.0959e-14, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.05it/s]


Epoch 9/9, Train Loss: 0.39998145913349764, Val Loss: 0.3742847903208299
tensor([[1.1827e-06, 1.0000e+00]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')
number of total kf=12


100%|██████████| 65/65 [00:13<00:00,  5.00it/s]


Epoch 1/9, Train Loss: 0.43234625140219246, Val Loss: 0.34352414516302254
tensor([[9.9999e-01, 1.0110e-05],
        [3.3374e-06, 1.0000e+00],
        [9.3660e-01, 6.3402e-02],
        [3.7168e-01, 6.2832e-01]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.01it/s]


Epoch 2/9, Train Loss: 0.4315696679453813, Val Loss: 0.3518810707789201
tensor([[9.9969e-01, 3.1175e-04],
        [3.9266e-04, 9.9961e-01],
        [9.9983e-01, 1.6641e-04],
        [4.7395e-03, 9.9526e-01]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.01it/s]


Epoch 3/9, Train Loss: 0.4397365127810995, Val Loss: 0.35408156697566695
tensor([[9.9899e-01, 1.0133e-03],
        [2.9673e-02, 9.7033e-01],
        [9.9951e-01, 4.8989e-04],
        [6.3144e-02, 9.3686e-01]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.16it/s]


Epoch 4/9, Train Loss: 0.41481569113622185, Val Loss: 0.3511482513867892
tensor([[1.0000e+00, 3.5666e-06],
        [1.9395e-01, 8.0605e-01],
        [1.0000e+00, 7.2038e-07],
        [3.8887e-02, 9.6111e-01]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.01it/s]


Epoch 5/9, Train Loss: 0.41557269924469575, Val Loss: 0.3368884104948777
Best model saved with validation loss: 0.3368884104948777
tensor([[1.0000e+00, 2.3045e-06],
        [1.2437e-02, 9.8756e-01],
        [9.9977e-01, 2.2575e-04],
        [1.9236e-03, 9.9808e-01]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.12it/s]


Epoch 6/9, Train Loss: 0.404867816062374, Val Loss: 0.3719601062627939
tensor([[1.0000e+00, 1.7040e-08],
        [1.0727e-03, 9.9893e-01],
        [9.9677e-01, 3.2266e-03],
        [3.0147e-06, 1.0000e+00]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:13<00:00,  5.00it/s]


Epoch 7/9, Train Loss: 0.40445871321299603, Val Loss: 0.34493397703537576
tensor([[9.9899e-01, 1.0107e-03],
        [8.6967e-04, 9.9913e-01],
        [9.9998e-01, 1.7020e-05],
        [1.9865e-04, 9.9980e-01]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.06it/s]


Epoch 8/9, Train Loss: 0.4287548297234164, Val Loss: 0.35554022513903105
tensor([[9.9994e-01, 6.0686e-05],
        [3.6982e-03, 9.9630e-01],
        [1.0000e+00, 1.7425e-08],
        [3.8749e-02, 9.6125e-01]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')


100%|██████████| 65/65 [00:12<00:00,  5.05it/s]


Epoch 9/9, Train Loss: 0.40837086111534643, Val Loss: 0.38292508125305175
tensor([[9.9946e-01, 5.3584e-04],
        [3.8653e-06, 1.0000e+00],
        [9.9970e-01, 3.0165e-04],
        [8.7078e-05, 9.9991e-01]], device='cuda:0')
tensor([[1, 0],
        [0, 1],
        [1, 0],
        [0, 1]], device='cuda:0')
number of total kf=12
number of total itteration=3
3


100%|██████████| 66/66 [00:12<00:00,  5.15it/s]


Epoch 1/9, Train Loss: 0.4142959711660866, Val Loss: 0.3629362005175966
Best model saved with validation loss: 0.3629362005175966
tensor([[2.8979e-04, 9.9971e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.93it/s]


Epoch 2/9, Train Loss: 0.4456141798095849, Val Loss: 0.42407014830545947
tensor([[3.7550e-04, 9.9962e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.85it/s]


Epoch 3/9, Train Loss: 0.4307539155920043, Val Loss: 0.3978279810963255
tensor([[9.1248e-04, 9.9909e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.95it/s]


Epoch 4/9, Train Loss: 0.4164883469352285, Val Loss: 0.3988971823092663
tensor([[0.0909, 0.9091]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  5.06it/s]


Epoch 5/9, Train Loss: 0.4096249844736725, Val Loss: 0.38679885232087335
tensor([[4.3300e-04, 9.9957e-01]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


100%|██████████| 66/66 [00:13<00:00,  4.98it/s]


Epoch 6/9, Train Loss: 0.4239022977479542, Val Loss: 0.38159057227048004
tensor([[0.2933, 0.7067]], device='cuda:0')
tensor([[0, 1]], device='cuda:0')


 37%|███▋      | 48/131 [00:09<00:13,  6.18it/s]

In [86]:
series_list=os.listdir('data')

In [94]:
with torch.no_grad():
    all_outputs=[]
    all_labels=[]
    for i in tqdm(series_list):
        input=standardize_dicom(i)
        input=input.float()
        input=input.to(device)
        output=model(input)
        output = output.cpu().detach().numpy()
        final_output=np.argmax(output)

        label=produce_label(i,train_label)
        label=label.cpu().detach().numpy()
        final_label=np.argmax(label)
        all_outputs.append(final_output)
        all_labels.append(final_label)


100%|██████████| 3132/3132 [09:30<00:00,  5.49it/s]


In [99]:
sum([o == l for o, l in zip(all_outputs, all_labels)]) / len(all_outputs)


0.8659003831417624

In [106]:

import pickle

# Save the lists to  Google Drive
with open('/content/drive/My Drive/all_labels.pkl', 'wb') as f:
  pickle.dump(all_labels, f)

with open('/content/drive/My Drive/all_outputs.pkl', 'wb') as f:
  pickle.dump(all_outputs, f)


In [107]:

from sklearn.metrics import f1_score

f1 = f1_score(all_labels, all_outputs, average='weighted')  # Calculate F1 score using 'weighted' average
print(f"F1 Score: {f1}")


F1 Score: 0.8836772546722171


In [93]:

from google.colab import files
import shutil

# Assuming 'best_model_path' variable holds the path to your best model
# Example: best_model_path = '/content/saved_models/best_model.pth'

# Define the destination path in your Google Drive
destination_path = '/content/drive/My Drive/best_model_dense_layer.pth'

# Copy the model file to your Google Drive
shutil.copy(best_model_path, destination_path)

print(f"Model weights saved to: {destination_path}")


Model weights saved to: /content/drive/My Drive/best_model_dense_layer.pth
